name: Fail on main
description: Exit workflow if GH action is targeting main branch
runs:
  using: 'composite'
  steps:
    - name: Check branch name
      id: check_branch_name
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "Error: Workflow cannot proceed on the main branch."
          exit 1
        fi
      shell: bash

